NoaLisaBookingRequestBundle:
    resource: "@NoaLisaBookingRequestBundle/Resources/config/routing.yml"
    prefix:   /

NoaLisaEntitiesSetBundle:
    resource: "@NoaLisaEntitiesSetBundle/Resources/config/routing.yml"
    prefix:   /

NoaLisaIndexBundle:
    resource: "@NoaLisaIndexBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
