parameters:
#    noa_lisa_index.example.class: NoaLisa\Bundle\IndexBundle\Example

services:
#    noa_lisa_index.example:
#        class: %noa_lisa_index.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
